# Generated by Django 3.1.1 on 2020-10-08 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_auto_20201007_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='werknemer_id',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
