# Generated by Django 3.1.1 on 2020-10-17 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
    ]
