# Generated by Django 3.1.1 on 2020-10-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'ongoing'), (1, 'done'), (2, 'stuck')], default=0),
        ),
    ]
